### ISSUE TITLE
remove CRT

### ISSUE THREAD

**Issue by victorminne** [CommandCrafterHD/Fallout4TerminalTheme#5]
Hi realy love the theme,
But i would prefer it without the CRT effect, can you help me in that ? I tried it myself but can't get results

Thanks to you, hoping for an answer.

**Comment by CommandCrafterHD** [comment]
Okay after some time I can actually respond to this in case anyone else wants to get rid of the CRT effect, simply try adding this to your custom CSS:

```css
body::before, .theme-dark .perksModal-fSYqOq::before,
.standardSidebarView-3F1I7i::before, .userPopout-3XzG_A::before,
.inner-1ilYF7::before, .container-1CE3eW::before, .resultsGroup-r_nuzN::before,
.theme-dark .root-1gCeng::after, .container-1r6BKw.themed-ANHk51::after,
.drawerSizingWrapper-17Mss4::after {
  display: none !important;
}
```

**Comment by Pecacheu** [comment]
I wanted to do the same thing but I found the code above isn't working anymore, probably due to some Discord updates since. I was able to figure out what does work with current Discord version as of now though.

```css
html, body::before, .root-2zfUH6::before, .standardSidebarView-E9Pc3j::before, .userPopout-2j1gM4::before, .inner-1ilYF7::before, .container-1Lk8p7::before, .resultsGroup-cfY57t::before, .theme-dark .root-g14mjS::after, .container-ZMc96U.themed-Hp1KC_::after, .drawerSizingWrapper-1txdWG::after, .layer-2aCOJ3::after, .container-ZMc96U::after, .quickswitcher-pKcM9U::after, .wrapper-3ByaVZ::after, .form-2oOOG9::after, .autocompleteInner-y1mjDl::after {
  background:none !important;
}
```

Personally I just wanted to disable the filter appearing over images because that's annoying in particular but it looks fine to me over controls and text. So to do that I used process of elimination and got it down to this:
```css
.root-g14mjS::after { background:none !important; }
```

Seems to work for every embed type (PNG, JPEG, GIF, link preview, and video) when clicked on, though I didn't thoroughly test.
